services:
  db:
    image: postgres:latest
    container_name: local_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: esteban
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: mydb
    volumes:
      - ./pgdata:/var/lib/postgresql/data
